name: Hello!
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show ubuntu detils
        run: lsb_release -a
      - name: Inspect files before checkout
        run: ls -la
      - name: Show current directory before checkout
        run: pwd
      - name: Checkout
        uses: actions/checkout@v4
      - name: Inspect files after checkout
        run: ls -la
      - name: Show current directory after checkout
        run: pwd
      - name: Show all branches after checkout
        run: git branch -a
      - name: Check rust commands
        run: |
          which rustup
          which cargo
