name: Release Test

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      # glibc version to 2.31
      image: ubuntu:20.04
    timeout-minutes: 30
    defaults:
      run:
        working-directory: rust_code
    steps:
      - name: Checkupt
        uses: actions/checkout@v4
      - name: Update and install packages
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update
          apt-get install -y unzip curl git autoconf build-essential ca-certificates tzdata
      - name: check glibc version
        run: ldd --version
      - name: Install rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update stable
          #rustup target add ${{ matrix.target }}
      - name: check rust version
        run: rustc --version
      - name: check cargo version
        run: cargo --version
      - name: Build package
        run: |
          cargo build --bin hello world
