name: Release Test

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      # glibc version to 2.31
      image: ubuntu:20.04
    timeout-minutes: 30
    defaults:
      run:
        working-directory: rust_code
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Update and install packages
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update
          apt-get install -y unzip curl git autoconf build-essential ca-certificates tzdata jq
      - name: check glibc version
        run: ldd --version
      - name: Install rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: install rust toolchain
        run: |
          rustup update --no-self-update stable
          #rustup target add ${{ matrix.target }}
      - name: check rust version
        run: rustc --version
      - name: check cargo version
        run: cargo --version
      - name: Build package
        run: |
          cargo build --release --bins
      - name: build archive
        shell: bash
        run: |
          dirname="hello-world-x86_64-unknown-linux-gnu"
          mkdir "$dirname"
          bins=$(cargo read-manifest --manifest-path Cargo.toml | jq -r '.targets[] | select(.kind[] | contains("bin")) | .name')
          for bin_name in $bins; do
            echo "Packaging $bin_name ..."
            cp "./target/release/$bin_name" "$dirname"
          done
          tar -czf "../$dirname.tar.gz" "$dirname"
          echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV
      - name: Release
        run: ls -l ..
