name: Rust

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Rust toolchai
      run: |
        rustup target add armv7-unknown-linux-musleabihf
        cargo install cross
    - name: Build
      run: |
        cross build --release --target armv7-unknown-linux-musleabihf

    - name: Check binary
      run: |
        ls -l ./target/armv7-unknown-linux-musleabihf/release/hello

    - name: Build archive
      shell: bash
      run: |
        dirname="hello-${GITHUB_REF#refs/tags/}-armv7-unknown-linux-musleabihf"
        mkdir "$dirname"
        mv "target/armv7-unknown-linux-musleabihf/release/hello" "$dirname"
        tar -czf "$dirname.tar.gz" "$dirname"
        echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.ASSET }}
