name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Rust toolchai
      run: |
        rustup target add armv7-unknown-linux-musleabihf
        cargo install cross
    - name: Build
      run: |
        cross build --release --target armv7-unknown-linux-musleabihf

    - name: Check binary
      run: |
        ls -l ./target/armv7-unknown-linux-musleabihf/release/hello
        ldd ./target/armv7-unknown-linux-musleabihf/release/hello
