name: Rust

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: rust_code
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabihf

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Rust toolchai
      run: |
        rustup target add ${{ matrix.target }}
        cargo install cross
    - name: Build
      run: |
        cross build --release --target ${{ matrix.target }}

    - name: Check binary
      run: |
        ls -l ./target/${{ matrix.target }}/release/hello

    - name: Build archive
      shell: bash
      run: |
        dirname="hello-${GITHUB_REF#refs/tags/}-${{ matrix.target }}"
        mkdir "$dirname"
        mv "target/${{ matrix.target }}/release/hello" "$dirname"
        tar -czf "../$dirname.tar.gz" "$dirname"
        echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.ASSET }}
